FROM golang:1.22.3 as builder

WORKDIR /ReforgerWhitelistAPI

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

RUN go build -o ReforgerWhitelistAPI .

FROM ubuntu:latest

WORKDIR /root/

COPY --from=builder /ReforgerWhitelistAPI .

COPY ./utils/test.sh .

ENV DATABASE_PATH :memory:

EXPOSE 8080

CMD ["sh", "./utils/test.sh"]
