FROM golang:1.22.3 as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

RUN go build -o rwapi .

FROM ubuntu:latest

RUN apk --no-cache add ca-certificates curl jq

WORKDIR /root/

COPY --from=builder /app/rwapi .

COPY test.sh .

ENV DATABASE_PATH :memory:

EXPOSE 8080

CMD ["sh", "./utils/test.sh"]
